---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pi4eme
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lmahdyyyy/pi4eme-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: pi4eme-config
            - secretRef:
                name: pi4eme-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pi4eme
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30000
